export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGGED_IN_USER ="LOGGED_IN_USER";

export const IS_LOADING_TRUE = 'IS_LOADING_TRUE';
export const IS_LOADING_FALSE = 'IS_LOADING_FALSE';
export const IS_LOADING_GLOBAL_TRUE = 'IS_LOADING_GLOBAL_TRUE';
export const IS_LOADING_GLOBAL_FALSE = 'IS_LOADING_GLOBAL_FALSE';